-- Migration: add_idempotency_key_to_transactions
-- Description: Adds idempotency_key column to prevent duplicate transaction charges
-- CRITICAL-003: Code Review Fix - Idempotency Implementation
-- Date: 2026-05-15

BEGIN;

-- Step 1: Add idempotency_key column as nullable (for existing data)
ALTER TABLE transactions ADD COLUMN IF NOT EXISTS idempotency_key VARCHAR(255);

-- Step 2: Create unique index on idempotency_key
-- This index enforces uniqueness at the database level
CREATE UNIQUE INDEX IF NOT EXISTS idx_transactions_idempotency_key
    ON transactions(idempotency_key)
    WHERE idempotency_key IS NOT NULL;

-- Step 3: Backfill existing transactions with legacy key
-- Format: legacy-{id} ensures all existing transactions have a unique key
UPDATE transactions
SET idempotency_key = CONCAT('legacy-', id::TEXT)
WHERE idempotency_key IS NULL;

-- Step 4: Add documentation
COMMENT ON COLUMN transactions.idempotency_key IS
    'Idempotency key to prevent duplicate charges from network retries. Generated by client (UUID v4). Unique across all transactions.';

-- Step 5: Make column NOT NULL for new transactions
-- After backfill, we can enforce NOT NULL constraint
ALTER TABLE transactions
    ALTER COLUMN idempotency_key SET NOT NULL;

-- Step 6: Recreate the unique index to include all rows (since now NOT NULL)
DROP INDEX IF EXISTS idx_transactions_idempotency_key;
CREATE UNIQUE INDEX idx_transactions_idempotency_key
    ON transactions(idempotency_key);

COMMIT;

-- Notes:
-- 1. The idempotency_key is generated by the mobile client using UUID v4
-- 2. Backend checks for existing transaction with same key before creating new one
-- 3. If duplicate key is received, backend returns existing transaction (idempotent response)
-- 4. This prevents duplicate charges when network retry occurs
-- 5. Legacy transactions use 'legacy-{id}' format to maintain uniqueness
